#ifndef VERSION_H
#define VERSION_H

#define KSB_VERSION_MAJOR 1
#define KSB_VERSION_MINOR 1
#define KSB_VERSION_PATCH 0
#define KSB_VERSION_STRING "1.1.0"
#define KSB_BUILD_DATE __DATE__
#define KSB_BUILD_TIME __TIME__

#endif // VERSION_H